name: mypy

on:
  workflow_call:
    inputs:
      cache-dependency-path:
        description: "Path to the Pipfile.lock"
        default: "Pipfile.lock"
        required: false
        type: string
      python-version:
        description: "Python version to be used"
        default: "3.7"
        required: false
        type: string
      runner:
        description: "GitHub runner label"
        default: "ubuntu-latest"
        required: false
        type: string

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
      - uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912  # v4.4.0
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pipenv"
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - name: Install dependencies
        run: |
          pipenv --python ${{ inputs.python-version }}
          pipenv install --dev
      - name: Run Mypy
        run: |
          pipenv run mypy
