name: mypy

on:
  workflow_call:
    inputs:
      cache-dependency-path:
        description: "Path to the Pipfile.lock"
        default: "Pipfile.lock"
        required: false
        type: string
      python-version:
        description: "Python version to be used"
        default: "3.7"
        required: false
        type: string
      runner:
        description: "GitHub runner label"
        default: "ubuntu-latest"
        required: false
        type: string

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ${{ inputs.runner }}
    env:
      MYPY_CACHE_DIR: ~/.cache/mypy
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f  # v3.4.0
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
        id: setup-python
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pipenv"
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - name: Install dependencies
        run: |
          pipenv --python ${{ inputs.python-version }}
          pipenv install --dev
      - uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0  # v3
        with:
          path: ${{ env.MYPY_CACHE_DIR }}
          key: mypy-${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles(inputs.cache-dependency-path) }}
      - name: Run Mypy
        run: |
          pipenv run mypy
