name: pre-commit

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to be used"
        default: "3.7"
        required: false
        type: string
      runner:
        description: "GitHub runner label"
        default: "ubuntu-latest"
        required: false
        type: string

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0  # v4.6.1
        with:
          python-version: ${{ inputs.python-version }}
      - name: pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507  # v3.0.0
