name: pre-commit

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to be used"
        default: "3.7"
        required: false
        type: string
      runner:
        description: "GitHub runner label"
        default: "ubuntu-latest"
        required: false
        type: string

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f  # v3.4.0
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
        with:
          python-version: ${{ inputs.python-version }}
      - name: pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507  # v3.0.0
